name: Create a new release and upload the solution to Azure blob storage CI

on:
  push:
    branches: release

jobs:
  main:
    uses: BeverCRM/Workflow-Build-Release-Upload-CI/.github/workflows/build-release-upload-ci.yml@master
    secrets: inherit
    # with:
    #   control-title: Sample Custom Component # required
    #   control-description: '' # default
    #   control-thumbnail-url: '' # default
    #   control-primary-image-url: '' # default
    #   control-youtube-video-url: '' # default
    #   control-img-extension: png # default
    #   control-tags: Bever-Controls, PCF, <control-title> # added by default
    #   create-new-release: true # default